// Generated by gencpp from file gazebo_ros_link_attacher/SetStatic.msg
// DO NOT EDIT!


#ifndef GAZEBO_ROS_LINK_ATTACHER_MESSAGE_SETSTATIC_H
#define GAZEBO_ROS_LINK_ATTACHER_MESSAGE_SETSTATIC_H

#include <ros/service_traits.h>


#include <gazebo_ros_link_attacher/SetStaticRequest.h>
#include <gazebo_ros_link_attacher/SetStaticResponse.h>


namespace gazebo_ros_link_attacher
{

struct SetStatic
{

typedef SetStaticRequest Request;
typedef SetStaticResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetStatic
} // namespace gazebo_ros_link_attacher


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_ros_link_attacher::SetStatic > {
  static const char* value()
  {
    return "45a69e9f7b70c39951d40d23f04ad0c9";
  }

  static const char* value(const ::gazebo_ros_link_attacher::SetStatic&) { return value(); }
};

template<>
struct DataType< ::gazebo_ros_link_attacher::SetStatic > {
  static const char* value()
  {
    return "gazebo_ros_link_attacher/SetStatic";
  }

  static const char* value(const ::gazebo_ros_link_attacher::SetStatic&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_ros_link_attacher::SetStaticRequest> should match
// service_traits::MD5Sum< ::gazebo_ros_link_attacher::SetStatic >
template<>
struct MD5Sum< ::gazebo_ros_link_attacher::SetStaticRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_ros_link_attacher::SetStatic >::value();
  }
  static const char* value(const ::gazebo_ros_link_attacher::SetStaticRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_ros_link_attacher::SetStaticRequest> should match
// service_traits::DataType< ::gazebo_ros_link_attacher::SetStatic >
template<>
struct DataType< ::gazebo_ros_link_attacher::SetStaticRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_ros_link_attacher::SetStatic >::value();
  }
  static const char* value(const ::gazebo_ros_link_attacher::SetStaticRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_ros_link_attacher::SetStaticResponse> should match
// service_traits::MD5Sum< ::gazebo_ros_link_attacher::SetStatic >
template<>
struct MD5Sum< ::gazebo_ros_link_attacher::SetStaticResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_ros_link_attacher::SetStatic >::value();
  }
  static const char* value(const ::gazebo_ros_link_attacher::SetStaticResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_ros_link_attacher::SetStaticResponse> should match
// service_traits::DataType< ::gazebo_ros_link_attacher::SetStatic >
template<>
struct DataType< ::gazebo_ros_link_attacher::SetStaticResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_ros_link_attacher::SetStatic >::value();
  }
  static const char* value(const ::gazebo_ros_link_attacher::SetStaticResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_ROS_LINK_ATTACHER_MESSAGE_SETSTATIC_H
